### ISSUE TITLE
Monitoring and cleanup of Docker disk space

### ISSUE THREAD

**Issue by davclark** [gigantum/gigantum-desktop#19] opened 2018-10-18 20:53 UTC
I'm calling this a bug, but it could be changed into an enhancement. I think it should be considered a bug because it's catastrophic when the problem manifests.

The problem is pretty simple. The electron app needs to know when docker is out of memory. We cannot rely on the client application (on the desktop), because it may fail to launch (e.g., when the image needs to be downloaded).

**Comment by dkleissa** [comment] 2019-03-21 21:17
duplicate of #29 - Could be clarified to provide auto-cleanup capabilities instead or simply closed

**Comment by Mazharrr** [comment] 2019-04-25 18:35
moving into gigantum client

**Closed by Mazharrr** 2019-04-25 18:35 UTC
Labels: bug, duplicate, feature, urgent
